### ISSUE TITLE
error

### ISSUE THREAD

**Issue by un-lock-me** [narratives-of-war/topic-rnn#2]
Hello,

Do you have any idea of this?

Thanks

Traceback (most recent call last):
  File "/home/saria/Downloads/topic-rnn-master/train_model.py", line 117, in <module>
    main()
  File "/home/saria/Downloads/topic-rnn-master/train_model.py", line 104, in main
    logger.info(model)
UnboundLocalError: local variable 'model' referenced before assignment

Process finished with exit code 1

**Comment by dangitstam** [comment]
Hi @saria85,

As of this moment, the code is fairly experimental. train_model.py as of this moment is geared toward TopicRNN (--model-type topic when running the file).

train_model.py and the repository in general also takes a JSON format that I haven't had the chance to outline in a README yet, and was written mostly for my research. Until master has been updated with a complete README on the format of the data needed as well as how to run all various parts of training / inference, the code will not be supported for users.

I was surprised by the interest in a model like this, I never planned on adding user support but now I'll make sure to make changes with the idea that others might be using this in the back of my mind :)

**Comment by un-lock-me** [comment]
thanks for replying back soon.

Yea actually I guess you will get more attention. this is a good model and can be extended for sure.
I have searched to find any other github project which is like this but still, all have some problems.
Ill keep watching this project, please update us once you got the chance to make it more user-friendly. 

Thanks

**Comment by laughinggu** [comment]
I am also interested in this model and wanna have a try. Do you have any chance to update the code?

Thanks a lot!

**Comment by dangitstam** [comment]
I'm planning a big overhaul, mainly, porting the code to AllenNLP so that experiments can be run with configs, vocabulary / tokenization would lean on a tried-and-true library instead of my own making, etc. Another thing I have to do is download the IMDB dataset to try to match the results of the paper to add validity to the code base. Right now in the dev branch, the results that come out of it are inconclusive until I do that.

**Comment by dangitstam** [comment]
Just a heads up, the AllenNLP refactor can be found here: https://github.com/dangitstam/topic-rnn

**As of now, there is no support for users but I plan on adding READMEs and robustness (i.e. tests and examples on how to set up your dataset) in the future. Although code is merged to master, that is personally just a checkpoint that I know runs properly.**

There also currently isn't topic printing or true language modeling yet (i.e. disallowing a full view of the text before allowing the VAE to make inference) but a lot of the guts are there.
